export const en = {
    nav: {
        features: "Platform Features",
        useCases: "Professional Use Cases",
        comparison: "Visual Model Comparison",
        pricing: "Flexible Pricing",
        inspiration: "Community Art",
        login: "Log In",
        tryIt: "Try It Now"
    },
    hero: {
        badge: "Powered by the advanced Google Nano Banana Pro model",
        title1: "Beyond Ultimate Imagination",
        title2: "AI Image Editor",
        desc: "Designed exclusively for creators pursuing boundless freedom and unique personality. Our platform combines advanced text-to-image capabilities, fast logical reasoning, and high-precision visual editing powered by Gemini and nano banana 2 to unleash your creative potential.",
        tryBtn: "Try It Now",
        videoBtn: "Image to Video",
        feature1: "One-time Edit",
        feature2: "Multi-image Support",
        feature3: "Natural Language"
    },
    editor: {
        title: "Try Our Editor Now",
        desc: "Experience the incredible power of our next-generation AI image editor.",
        mixboard: "Go to Mixboard",
        modelSelect: "Model Selection",
        prompt: "Input Prompt",
        promptPlaceholder: "Describe the image you want to generate with our engine...",
        promptDefault: "A mechanical cat wearing a cyberpunk jacket on a neon-lit rainy street, cinematic lighting, ultra high 8k resolution generated by nano banana 2.",
        generate: "Generate Image",
        uploadRef: "Upload Reference",
        download: "Download Asset",
        variation: "Generate Variation",
        points: "reward pts"
    },
    editorPanel: {
        promptLabel: "Prompt",
        promptHelp: "A text description of the image you want to generate",
        imageInputLabel: "image_input",
        uploadHint: "Click to upload or drag and drop",
        fileSupportHint: "JPEG, PNG, WEBP. Max 30MB each. Up to {{count}} files",
        selectFiles: "Select files",
        removeFileAria: "Remove {{fileName}}",
        imageInputHelp: "Input images to transform or use as reference (optional)",
        aspectRatioLabel: "aspect_ratio",
        aspectRatioHelp: "Aspect ratio of the generated image",
        googleSearchLabel: "google_search",
        googleSearchHelp: "Use real-time Google Web Search grounding",
        resolutionLabel: "resolution",
        resolutionHelp: "Higher resolution may take longer to generate",
        outputFormatLabel: "output_format",
        outputFormatHelp: "Format of the generated image",
        reset: "Reset",
        runWithCredits: "{{credits}} Run",
        outputTypeLabel: "output type",
        outputTypeImage: "image",
        previewAlt: "Nano Banana preview",
        previewEmptyTitle: "Preview appears here",
        previewEmptyDesc: "Run with only prompt, or upload images and run with prompt.",
        generatingImage: "Generating image...",
        statusLabel: "Status",
        statusGenerating: "Generating... {{progress}}%",
        statusFailed: "Failed",
        statusComplete: "Complete",
        statusReady: "Ready",
        elapsedGenerated: "Generated in {{seconds}} seconds",
        elapsedWaiting: "Waiting for generation",
        unsupportedFileType: "Unsupported file type",
        fileTooLarge: "Exceeds 30MB",
        maxImagesAllowed: "Only {{count}} images are allowed.",
        promptRequired: "Please enter a prompt before generating.",
        loginRequired: "Please sign in before generating an image.",
        creditsInsufficient: "Insufficient credits. Please upgrade or recharge before generating.",
        generationFailed: "Generation failed.",
        missingTaskId: "Missing Task ID",
        taskCreateError: "An error occurred during task creation.",
        taskQueryFailed: "Failed to query task status.",
        taskFailedServer: "Task failed on server."
    },
    brand: {
        title1: "Enter the amazing",
        title2: "nano banana 2 Universe",
        p1: "We believe that every great artistic work starts with a brilliant idea. This advanced platform is not just a simple tool; it is a comprehensive creative environment designed specifically for you.",
        p2: "Here, we emphasize creative freedom over the strict rigor of traditional software. It is meticulously crafted for modern creators who value absolute flexibility, letting your imagination run wild through the power of gemini nano banana 2."
    },
    howItWorks: {
        title: "How nano banana 2 Works",
        desc: "Experience the power of our engine and transform your ideas into visual masterpieces in just a few simple steps.",
        steps: [
            { title: "Describe Idea", desc: "Enter your prompt in detail, letting the AI deeply understand your unique visual intent." },
            { title: "Smart Generation", desc: "Our powerful nano banana 2 engine uses complex logical reasoning to instantly present clear images." },
            { title: "Advanced Editing", desc: "Use intuitive tools to adjust details and export the perfect final artwork." }
        ]
    },
    features: {
        title: "Core Platform Capabilities",
        desc: "Powered by advanced AI models, providing unprecedented image generation control.",
        items: [
            { title: "Advanced AI Reasoning", desc: "Deeply understand text prompts and apply logical reasoning to generate accurate images." },
            { title: "3D Object Editing", desc: "Understand spatial relationships in 2D images for precise object manipulation." },
            { title: "Smart Image Generation", desc: "Transform simple text descriptions into highly realistic visual masterpieces efficiently." },
            { title: "Consistency Protection", desc: "Maintain character, style, and environment visual consistency during complex editing processes." },
            { title: "Deep Prompt Understanding", desc: "Utilize powerful logical reasoning to handle multi-layered tasks." },
            { title: "Context-Aware Editing", desc: "Combine deep learning algorithms to truly understand your creative intent and execute it perfectly." }
        ]
    },
    comparison: {
        title: "Beyond Existing Platform Limits",
        desc: "Compared to traditional industry tools, nano banana 2 shows overwhelming advantages in all core capabilities, powered by the advanced features of the Gemini models.",
        dimensions: "Core System Dimensions",
        items: [
            "Complex Logical Reasoning",
            "3D Object Manipulation",
            "Precise Text Retention",
            "Deep Spatial Understanding",
            "Overall Editing Consistency",
            "Complex Prompt Understanding"
        ],
        examples: [
            "Turn environment water pink",
            "Character substitution plus style transfer",
            "Advanced clothing material texture editing"
        ],
        realEffect: "Real Visual Effect Comparison using Google nano banana 2"
    },
    inspiration: {
        title: "Community Inspiration Gallery",
        desc: "Explore a curated collection of stunning digital artworks and creative platform designs generated by global creators. Discover exactly what professional users are building with nano banana 2 today.",
        viewMore: "View More Inspiration from the community",
        viewDetails: "View Creation Details"
    },
    useCases: {
        title: "Infinite Practical Use Cases",
        items: [
            { title: "Product Design", desc: "Precisely control fine product visual details, generate diverse marketing images, and improve conversion rates." },
            { title: "Social Content Creation", desc: "Generate eye-catching, high-quality digital content optimized for social media feeds and marketing assets using our platform." },
            { title: "Digital Art", desc: "Materialize abstract conceptual ideas, break through traditional limits, and explore new visual art styles." },
            { title: "Historical Photo Restoration", desc: "Utilize the powerful AI logical reasoning capabilities to restore old or damaged family photos." }
        ]
    },
    pricing: {
        title: "Choose Your Flexible Plan",
        monthly: "Billed Monthly",
        annually: "Billed Annually",
        starter: "Standard Starter Plan",
        pro: "Professional Pro Plan",
        enterprise: "Corporate Enterprise",
        month: "per month",
        billedAnnually: "Billed annually",
        custom: "Custom Tailored",
        tailored: "Specifically tailored to your business needs",
        getStarted: "Get Started",
        contactSales: "Contact Sales",
        mostPopular: "Most Popular",
        starterFeatures: [
            "5,000 computation credits per month for core tasks",
            "Up to exactly 100 high quality images per day",
            "Basic image editing and enhancement features",
            "Standard high definition resolution"
        ],
        proFeatures: [
            "18,000 premium high priority computation credits per month",
            "Generate up to 500 images per day with Google nano banana 2",
            "Advanced AI 3D object manipulation capabilities",
            "Ultra high definition resolution",
            "Full commercial developer API access"
        ],
        enterpriseFeatures: [
            "Unlimited credits for infinite generation tasks",
            "Cinematic outputs up to an incredible 8K resolution",
            "Dedicated and independent private server API node",
            "Direct 24/7 dedicated priority technical enterprise support",
            "Custom proprietary gemini nano banana 2 model architectural fine-tuning"
        ]
    },
    testimonials: {
        title: "Creators' Voices",
        roles: ["Digital Creator", "UGC Creative Expert", "Professional Image Retoucher"],
        contents: [
            "This platform is among the strongest in maintaining character consistency. It allows me to easily create coherent visual comic stories.",
            "Creating customized digital AI influencers has never been easier. Semantic understanding is extremely strong.",
            "The end result visual effect of a single edit with gemini nano banana 2 is truly amazing. Its advanced 3D object spatial manipulation feature allows exact precise adjustments."
        ]
    },
    faq: {
        title: "Frequently Asked Questions",
        qs: [
            "What exactly is nano banana 2 AI?",
            "Is there a completely free trial plan available?",
            "How is nano banana 2 fundamentally different from other platforms?",
            "What are the specific major upgrade highlights of this new version?",
            "What is its exact technological relationship with Gemini?",
            "Are there any strict legal restrictions?"
        ],
        as: [
            "nano banana 2 is a professional image editor built on advanced foundational AI models, designed for expert digital creators.",
            "We offer free digital trial computation credits to seamlessly experience the core features of the platform.",
            "It possesses significant architectural advantages in complex logical reasoning and 3D spatial object manipulation, enabling gemini nano banana 2 to successfully execute complex edits.",
            "The foundational AI engine drastically improves initial generation speed and officially introduces a brand new context-aware intelligent editing engine fully optimized for nano banana 2.",
            "The core underlying computational logic capabilities are supported by Google technology, deeply optimized through gemini nano banana 2 applied for complex Visual Image related tasks.",
            "We adhere to ethical guidelines and prohibit generating any illegal content. Please refer to our official Terms of Service."
        ]
    },
    cta: {
        title1: "Are you ready to experience",
        title2: "Google Nano Banana?",
        desc: "Join our exclusive waitlist today and be among the first creators to experience the powerful visual interactive charm of our platform. Start unleashing your creative potential with advanced AI capabilities right now.",
        signup: "Sign Up Now",
        demo: "Try Demo"
    },
    footer: {
        desc: "A premium next-generation AI visual editor built on the latest architectural models. It is designed and optimized for modern digital industry creators who pursue artistic freedom and unique personality, dynamically powered by Google nano banana 2.",
        related: "Related Official Products by gemini nano banana 2",
        legal: "Official Legal Info",
        privacy: "Privacy Policy",
        terms: "Terms of Service",
        contact: "Contact Support",
        rights: "Copyright © 2026 nano banana 2. All specific related commercial legal rights strictly rigorously reserved."
    }
};
